const CartActionTypes = {
    TOGGLE_CART_HIDDEN : "TOGGLE_CART_HIDDEN",
    CART_CLICK_OUTSIDE : "CART_CLICK_OUTSIDE",
    ADD_ITEM : "ADD_ITEM",
    ADD_ITEMS : "ADD_ITEMS",
    REMOVE_ITEM: "REMOVE_ITEM",
    CLEAR_ITEM_FROM_CART : "CLEAR_ITEM_FROM_CART",
    CLEAR_CART : "CLEAR_CART"
}
export default CartActionTypes;