const PaymentActionTypes = {
    STRIPE_PAYMENT_START : "STRIPE_PAYMENT_START",
    STRIPE_PAYMENT_SUCCESS : "STRIPE_PAYMENT_SUCCESS",
    STRIPE_PAYMENT_FAILURE : "STRIPE_PAYMENT_FAILURE"
}

export default PaymentActionTypes;