export const UserActionTypes = {
    SET_CURRENT_USER :"SET_CURRENT_USER",
    TOGGLE_USER_DROPDOWN_HIDDEN: "TOGGLE_USER_DROPDOWN_HIDDEN",
    USER_DROPDOWN_CLICKED_OUTSIDE : "USER_DROPDOWN_CLICKED_OUTSIDE",
    SHOW_USER_INFORMATION : "SHOW_USER_INFORMATION",
    SHOW_RESET_PASSWORD : "SHOW_RESET_PASSWORD",
    SHOW_ORDER_HISTORY : "SHOW_ORDER_HISTORY"
}