export const UserActionTypes = {
    SET_CURRENT_USER :"SET_CURRENT_USER",
    TOGGLE_USER_DROPDOWN_HIDDEN: "TOGGLE_USER_DROPDOWN_HIDDEN",
    USER_DROPDOWN_CLICKED_OUTSIDE : "USER_DROPDOWN_CLICKED_OUTSIDE"
}