const UserActionTypes = {
    SET_CURRENT_USER :"SET_CURRENT_USER",
    
    GOOGLE_SIGN_IN_START : "GOOGLE_SIGN_IN_START",
    EMAIL_SIGN_IN_START : "EMAIL_SIGN_IN_START",
    SIGN_IN_SUCCESS : "SIGN_IN_SUCCESS",
    SIGN_IN_FAILURE : "SIGN_IN_FAILURE",
    CHECK_USER_SESSION : "CHECK_USER_SESSION",
    SIGN_OUT_START : "SIGN_OUT_START",
    SIGN_OUT_SUCCESS : "SIGN_OUT_SUCCESS",
    SIGN_OUT_FAILURE : "SIGN_OUT_FAILURE",
    SIGN_UP_START : "SIGN_UP_START",
    SIGN_UP_SUCCESS : "SIGN_UP_SUCCESS",
    SIGN_UP_FAILURE : "SIGN_UP_FAILURE",

    UPDATE_ADDRESS_START : "UPDATE_ADDRESS_START",
    UPDATE_ADDRESS_SUCCESS : "UPDATE_ADDRESS_SUCCESS",
    UPDATE_ADDRESS_FAILURE : "UPDATE_ADDRESS_FAILURE",

    TOGGLE_USER_DROPDOWN_HIDDEN: "TOGGLE_USER_DROPDOWN_HIDDEN",
    USER_DROPDOWN_CLICKED_OUTSIDE : "USER_DROPDOWN_CLICKED_OUTSIDE",
    SHOW_USER_INFORMATION : "SHOW_USER_INFORMATION",
    SHOW_RESET_PASSWORD : "SHOW_RESET_PASSWORD",
    SHOW_ORDER_HISTORY : "SHOW_ORDER_HISTORY"
}

export default UserActionTypes;